baseURL = "https://kursadyanik.com/"
languageCode = "tr-tr"
title = "kursadyanik.com"
theme = "PaperMod"
buildFuture = true
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  mainSections = ["posts"]
  homeInfoParams = { Title = "", Content = "Cybersecurity & Notes." }
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowShareButtons = false
  defaultTheme = "dark"
  disableThemeToggle = true

  # SEO bilgileri
  description = "Cyber Security - kursadyanik.com"
  author = "kursad."
  keywords = ["siber güvenlik", "cybersecurity", "osint", "bilgi güvenliği", "kursadyanik", "blog" , "ctf"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Ana Sayfa"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "Hakkında"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "İletişim"
    url = "/contact/"
    weight = 3
